### ISSUE TITLE
No Python virtual environment available. Exit.

### ISSUE THREAD

**Issue by arehbein** [fhempy/fhempy#248] opened 2023-12-17 19:54 UTC
My fhempy instance has been working previously.
However, I have been updating my whole system (Debian 11.8, FHEM and fhempy) recently and now my fhempy server does nto start anymore.

It always loops into the below error:

`No Python virtual environment available. Exit.
Activating virtual environment...FHEM/bindings/python/bin/fhempy: line 55: .fhempy/fhempy_venv/bin/activate: No such file or directory
OK
No Python virtual environment available. Exit.
Activating virtual environment...FHEM/bindings/python/bin/fhempy: line 55: .fhempy/fhempy_venv/bin/activate: No such file or directory
OK`

**Comment by fhempy** [comment] 2023-12-17 19:56
Are you running fhempy within a docker container? Please try to delete .fhempy/fhempy_venv directory and see if it works.

**Comment by arehbein** [comment] 2023-12-17 19:58
No, it is a regular DietPI instance. Let me delete it and reboot...

**Comment by fhempy** [comment] 2023-12-17 19:59
Which python version do you use?

**Comment by fhempy** [comment] 2023-12-17 20:00
Please search the log for `Creating fhempy virtual environment` and post the error which should have happened there so that I can see the root cause.

**Comment by arehbein** [comment] 2023-12-17 20:01
# python3 --version
Python 3.9.2

There was a missing package and I followed the instruction to add the venv package.
Now only the above mentioned errors shows up.

**Comment by arehbein** [comment] 2023-12-17 20:02
Immediately after mv'ing the venv directory, the following error is shown in the log file:

`No Python virtual environment available. Exit.
Activating virtual environment...FHEM/bindings/python/bin/fhempy: line 55: .fhempy/fhempy_venv/bin/activate: No such file or directory
OK
No Python virtual environment available. Exit.
Creating fhempy virtual environment...OK
Activating virtual environment...OK
2023-12-17 21:00:32,585 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/start_fhempy.py", line 141, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2023-12-17 21:00:32,587 - INFO     - __main__: Attempting install of fhempy>=0.1.462`

**Comment by arehbein** [comment] 2023-12-17 20:03
Wait... Now, server and bindings show green and seem to run again...

**Comment by fhempy** [comment] 2023-12-17 20:06
I think I found the bug. If the python3-venv package was missing on the first run, it didn't do a venv creation again. Should be fixed now.

**Comment by arehbein** [comment] 2023-12-17 20:09
The server runs again and the RCT binding too; only the skoda one is not at the moment...

**Comment by fhempy** [comment] 2023-12-17 20:13
Please try again in 10min with the new version. I updated the skodaconnect library to the latest version. If it doesn't work, please open a new issue. Thx!

**Closed by fhempy** 2023-12-17 20:13 UTC

**Comment by arehbein** [comment] 2023-12-17 20:25
..updated skodaconnect lib fixed the token issue! thanks.
